# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 658)
        MainWindow.setMinimumSize(QtCore.QSize(256, 256))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setSortingEnabled(True)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setEnabled(False)
        self.actionVersion.setObjectName("actionVersion")
        self.actionRealtime = QtWidgets.QAction(MainWindow)
        self.actionRealtime.setCheckable(True)
        self.actionRealtime.setChecked(True)
        self.actionRealtime.setObjectName("actionRealtime")
        self.actionAudible_Blink = QtWidgets.QAction(MainWindow)
        self.actionAudible_Blink.setCheckable(True)
        self.actionAudible_Blink.setChecked(False)
        self.actionAudible_Blink.setObjectName("actionAudible_Blink")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionColumns = QtWidgets.QAction(MainWindow)
        self.actionColumns.setObjectName("actionColumns")
        self.actionGrouping = QtWidgets.QAction(MainWindow)
        self.actionGrouping.setObjectName("actionGrouping")
        self.actionFormat = QtWidgets.QAction(MainWindow)
        self.actionFormat.setObjectName("actionFormat")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionFit_Columns_To_Contents = QtWidgets.QAction(MainWindow)
        self.actionFit_Columns_To_Contents.setObjectName("actionFit_Columns_To_Contents")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionVersion)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuView.addAction(self.actionColumns)
        self.menuView.addAction(self.actionGrouping)
        self.menuView.addAction(self.actionFormat)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFit_Columns_To_Contents)
        self.menuView.addAction(self.actionClear)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRealtime)
        self.menuView.addAction(self.actionAudible_Blink)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aswan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionVersion.setText(_translate("MainWindow", "Version 0.0.3"))
        self.actionRealtime.setText(_translate("MainWindow", "Realltime"))
        self.actionAudible_Blink.setText(_translate("MainWindow", "Audible Blink"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionColumns.setText(_translate("MainWindow", "Columns..."))
        self.actionGrouping.setText(_translate("MainWindow", "Grouping..."))
        self.actionFormat.setText(_translate("MainWindow", "Format..."))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionFit_Columns_To_Contents.setText(_translate("MainWindow", "Fit Columns To Contents"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
